### PR TITLE
Enable 'set -e' in gen_binaries.sh for more robust builds

### PR DESCRIPTION
**Pull request by NathanTP**
There were a few lines that returned non-zero exit codes even when they worked. This probably wasn't a huge issue when manually running Speckle, but it makes it hard to wrap. In my case, I was making a FireMarshal workload for SPEC2017 to make it as easy as possible to run on FireSim. The workload would build just fine, and the run scripts would fail with some cryptic message.

I'm happy to also make another PR for the main 2017 branch if there's interest.

### CODE REVIEW

**Review by davidbiancolin — APPROVED** [review]
LGTM

**Comment by davidbiancolin** [comment]
We can probably just drop the firesim branch if you can remove the platform specific stuff.

**Comment by ccelio** [comment]
Nathan, let me know when you want me to merge this, if you guys don't have commit privileges.

**Comment by NathanTP** [comment]
I don't have commit privilege, merge away.

As for @davidbiancolin's suggestion of merging into the mainline 2017 branch I'll make a draft PR and we can discuss there.

**Pull request merged**
